sudo: required
language: node_js
node_js:
- node

before_install:
  - echo "Before Install"

script:
  - echo "Script"

before_deploy:
  - echo "BEfore deploy"

deploy:
  - chmod +x deploy.sh
  - "./deploy.sh"